=== JavierUribeMontoyaEngineer/ArquitecturaSoftware/UribeMontoya-Javier-entrega1/xml/schema/programa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.um.es/programasRTVE"
	xmlns:tns="http://www.um.es/programasRTVE" elementFormDefault="qualified">

	<simpleType name="tipoUrl">
		<restriction base="string">
			<pattern value="http://www.rtve.es/m/.*" />
		</restriction>
	</simpleType>

	<element name="programa">
		<complexType>
			<sequence>
				<element name="nombre" type="string" />
				<element name="emision" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="titulo" type="string" />
							<element name="url" type="tns:tipoUrl" />
						</sequence>
						<attribute name="fecha" type="date" use="required" />
						<attribute name="tiempo" use="required">
							<simpleType>
								<restriction base="string">
									<pattern value="[0-9][0-9]:([0-5][0-9]):[0-5][0-9]" />
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
				<element name="productoAmazon" minOccurs="0" maxOccurs="3"
					type="tns:productoAmazon"></element>
			</sequence>
			<attribute name="id" type="string" use="required" />
			<attribute name="urlPrograma" type="tns:tipoUrl" use="required"></attribute>
			<attribute name="urlImagen" use="required">
				<simpleType>
					<restriction base="string">
						<pattern value="http://img.rtve.es/imagenes/.*\.(png|jpg|gif)" />
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<complexType name="productoAmazon">
		<attribute name="ASIN" use="required" type="NMTOKEN"></attribute>
		<attribute name="titulo" use="required" type="string"></attribute>
		<attribute name="smallImage" use="required" type="anyURI"></attribute>
		<attribute name="largeImage" use="required" type="anyURI"></attribute>
		<attribute name="precioMasBajo" use="required" type="float"></attribute>
		<attribute name="urlDetallesProducto" use="required" type="anyURI"></attribute>
	</complexType>
</schema>

=== JavierUribeMontoyaEngineer/ArquitecturaSoftware/UribeMontoya-Javier-entrega1/xml/schema/programa.xml
<?xml version="1.0" encoding="UTF-8"?>

<programa xmlns="http://www.um.es/programasRTVE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.um.es/programasRTVE programa.xsd" id="acacias-38"
	urlPrograma="http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve"
	urlImagen="http://img.rtve.es/imagenes/acacias-38/1425305370705.png">

	<nombre>Acacias 38</nombre>
	<emision fecha="2017-02-28" tiempo="00:54:44">
		<titulo>Capítulo 447</titulo>
		<url>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-447/3898958/?media=tve</url>
	</emision>
	<emision fecha="2017-02-02" tiempo="00:55:50">
		<titulo>Capítulo 446</titulo>
		<url>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-446/3897001/?media=tve</url>
	</emision>
</programa>
