=== JavierUribeMontoyaEngineer/ArquitecturaSoftware/UribeMontoya-Javier-entrega1/xml/dtd/programa.dtd
<!ELEMENT programa (nombre, emision+)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT emision (titulo, url)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ATTLIST programa
	id NMTOKEN #REQUIRED
	urlPrograma CDATA #REQUIRED
	urlImagen CDATA #REQUIRED>

<!ATTLIST emision
	fecha CDATA #REQUIRED
	tiempo CDATA #REQUIRED>

=== JavierUribeMontoyaEngineer/ArquitecturaSoftware/UribeMontoya-Javier-entrega1/xml/dtd/programa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programa SYSTEM "programa.dtd">
<programa id="acacias-38"
	urlPrograma="http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve"
	urlImagen="http://img.rtve.es/imagenes/acacias-38/1425305370705.png">

	<nombre>Acacias 38</nombre>
	<emision fecha="03/02/2017" tiempo="00:54:44">
		<titulo>Capítulo 447</titulo>
		<url>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-447/3898958/?media=tve</url>
	</emision>
	<emision fecha="02/02/2017" tiempo="00:55:50">
		<titulo>Capítulo 446</titulo>
		<url>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-446/3897001/?media=tve</url>
	</emision>
</programa>
